import assert from "node:assert/strict";
import { CORE_STATS, PLAYERS, STATLINE_STATS } from "../src/data/players.js";
import { createDailyPuzzle, createRandomPuzzle, createStatlineDailyPuzzle, dateId, puzzleNumber } from "../src/game/puzzle.js";
import { comparePlayer, equivalentProfiles } from "../src/game/comparisons.js";
import { createGameState, scoutStat, submitGuess } from "../src/game/gameState.js";
import { filterCandidates } from "../src/game/filtering.js";
import { getStatRange, valueFallsInRange } from "../src/game/statRanges.js";
import { STATLINE_MAX_ATTEMPTS, compareTiers, createStatlineState, getStatTier, playerTiers, scoreFirstGuess, submitStatlineGuess } from "../src/game/statlineState.js";
import { guessHistoryMarkup } from "../src/ui/guessHistory.js";

assert.deepEqual(getStatRange(0), { min: 0, max: 25, label: "0-25" });
assert.equal(dateId(new Date(2026, 8, 5, 12, 0)), "2026-09-05");
assert.equal(puzzleNumber("2026-09-05"), 1 + Math.floor((new Date(2026, 8, 5, 0, 0, 0).getTime() - new Date(2026, 0, 1).getTime()) / 86_400_000));
assert.deepEqual(getStatRange(25), { min: 0, max: 25, label: "0-25" });
assert.deepEqual(getStatRange(26), { min: 26, max: 50, label: "26-50" });
assert.deepEqual(getStatRange(50), { min: 26, max: 50, label: "26-50" });
assert.deepEqual(getStatRange(51), { min: 51, max: 75, label: "51-75" });
assert.deepEqual(getStatRange(74), { min: 51, max: 75, label: "51-75" });
assert.deepEqual(getStatRange(76), { min: 76, max: 100, label: "76-100" });
assert.deepEqual(getStatRange(100), { min: 76, max: 100, label: "76-100" });
assert(valueFallsInRange(74, getStatRange(74)));
assert(!valueFallsInRange(80, getStatRange(50)));

const pablo = PLAYERS.find((player) => player.name === "Pablo Sanchez");
const kenny = PLAYERS.find((player) => player.name === "Kenny Kawaguchi");
assert.deepEqual(STATLINE_STATS.map(({ label }) => label), ["Bat Power", "Bat Contact", "Stamina", "Speed", "Coordination", "Arm Strength", "Arm Accuracy", "Eye"]);
assert.equal(getStatTier(100), "S+");
assert.equal(getStatTier(85), "S");
assert.equal(getStatTier(70), "A");
assert.equal(getStatTier(55), "B");
assert.equal(getStatTier(40), "C");
assert.equal(getStatTier(21), "D");
assert.equal(getStatTier(1), "E");
assert.equal(compareTiers("B", "A"), "higher");
assert.equal(compareTiers("S", "A"), "lower");
assert.equal(compareTiers("A", "A"), "correct");
const puzzle = createDailyPuzzle(PLAYERS, "2026-09-05", pablo.id);
assert.deepEqual(puzzle, createDailyPuzzle(PLAYERS, "2026-09-05", pablo.id));
assert.deepEqual(puzzle.startingStats, []);
const statlinePuzzle = createStatlineDailyPuzzle(PLAYERS, "2026-09-05");
assert.deepEqual(statlinePuzzle, createStatlineDailyPuzzle(PLAYERS, "2026-09-05"));
assert.notEqual(statlinePuzzle.mysteryId, createDailyPuzzle(PLAYERS, "2026-09-05").mysteryId);
assert.equal(createStatlineDailyPuzzle(PLAYERS, "2026-09-05", pablo.id).mysteryId, pablo.id);
let statlineState = createStatlineState(puzzle);
statlineState = { ...statlineState, guesses: Object.fromEntries(STATLINE_STATS.map(({ key }) => [key, "E"])) };
statlineState = submitStatlineGuess(statlineState, pablo);
assert.equal(statlineState.attempt, 1);
assert.equal(statlineState.firstGuessScore, scoreFirstGuess(statlineState.firstGuessTiers, pablo));
assert.equal(statlineState.feedback.battingPower, "higher");
assert.deepEqual(statlineState.submittedGuesses, statlineState.history[0].guesses);
assert.deepEqual(statlineState.history[0].guesses, statlineState.firstGuessTiers);
assert.deepEqual(statlineState.history[0].feedback, statlineState.feedback);
assert.deepEqual(statlineState.guesses, {});
assert(statlineState.lockedStats.every((key) => statlineState.feedback[key] === "correct"));
assert.throws(() => submitStatlineGuess({ ...statlineState, guesses: Object.fromEntries(STATLINE_STATS.map(({ key }) => [key, "E"])) }, pablo));
const preservedFirstGuessScore = statlineState.firstGuessScore;
statlineState = { ...statlineState, guesses: playerTiers(pablo) };
statlineState = submitStatlineGuess(statlineState, pablo);
assert.equal(statlineState.status, "won");
assert.equal(statlineState.firstGuessScore, preservedFirstGuessScore);
let statlineLoss = createStatlineState(puzzle);
for (const tier of ["E", "D", "C"]) {
	statlineLoss = { ...statlineLoss, guesses: Object.fromEntries(STATLINE_STATS.map(({ key }) => [key, tier])) };
	statlineLoss = submitStatlineGuess(statlineLoss, pablo);
}
assert.equal(statlineLoss.status, "lost");
const randomPuzzle = createRandomPuzzle(PLAYERS, "test-round");
assert.deepEqual(randomPuzzle, createRandomPuzzle(PLAYERS, "test-round"));
assert.equal(randomPuzzle.id, "random-test-round");
assert(PLAYERS.some((player) => player.id === randomPuzzle.mysteryId));
assert.equal(createStatlineState(randomPuzzle).puzzleId, randomPuzzle.id);
assert.equal(comparePlayer(kenny, pablo).battingPower, "higher");
assert.equal(comparePlayer(pablo, pablo).speed, "equal");
const equivalentPair = PLAYERS.find((player, index) => PLAYERS.slice(index + 1).some((other) => equivalentProfiles(player, other)));
const equivalentGuess = PLAYERS.find((player) => player.id !== equivalentPair.id && equivalentProfiles(player, equivalentPair));
assert(equivalentProfiles(equivalentPair, equivalentGuess));
let state = createGameState(puzzle);
assert.deepEqual(state.revealedStats, []);
assert.equal(state.scoutTokens, 2);
assert.equal(state.scoutsThisGuess, 0);
assert.deepEqual(state.scoutedStats, {});
assert.throws(() => scoutStat(state, "speed", pablo));
state = submitGuess(state, kenny, pablo);
assert.equal(Object.keys(state.guesses[0].comparisons).length, CORE_STATS.length);
assert.deepEqual(state.guesses[0].comparisons, comparePlayer(kenny, pablo));
assert.deepEqual(state.guesses[0].possibleRanges.speed, state.possibleRanges.speed);
assert.equal(state.possibleRanges.speed.label, comparePlayer(kenny, pablo).speed === "higher" ? `${kenny.speed + 1}-100` : `${0}-${kenny.speed - 1}`);
const rangeMarkup = guessHistoryMarkup(state.guesses, state.possibleRanges);
assert.match(rangeMarkup, new RegExp(`>${state.possibleRanges.speed.min}<`));
assert.match(rangeMarkup, new RegExp(`>${state.possibleRanges.speed.max}<`));
assert.doesNotMatch(rangeMarkup, /preview-range-indicator|aria-label="(?:in range|out of range)"/);
assert.equal((guessHistoryMarkup(state.guesses).match(/(?:⬆️|⬇️|✅)/g) || []).length, CORE_STATS.length);
assert.equal((guessHistoryMarkup(state.guesses).match(/aria-label="(?:higher|lower|equal)"/g) || []).length, CORE_STATS.length);
assert.equal((guessHistoryMarkup(state.guesses).match(/<article class="guess-row empty-guess-row"><h3>#\d+: -----<\/h3><\/article>/g) || []).length, 4);
assert.equal((guessHistoryMarkup(state.guesses).match(/empty-guess-row[\s\S]*?(?:report-header|history-stats)/g) || []).length, 0);
assert.equal((guessHistoryMarkup(state.guesses).match(/Possible:/g) || []).length, 0);
assert.throws(() => submitGuess(state, kenny, pablo));
const beforeClue = filterCandidates(PLAYERS, state, pablo).length;
assert.equal(filterCandidates(PLAYERS, state, pablo).length, beforeClue);
const speedRange = getStatRange(pablo.speed);
assert(PLAYERS.some((player) => player.speed !== pablo.speed && valueFallsInRange(player.speed, speedRange)));
const rangeOnlyState = scoutStat(state, "speed", pablo);
assert(filterCandidates(PLAYERS, rangeOnlyState, pablo).some((player) => player.speed !== pablo.speed));
const directionalOnlyState = { ...rangeOnlyState, guesses: state.guesses };
assert.equal(filterCandidates(PLAYERS, directionalOnlyState, pablo).length, filterCandidates(PLAYERS, rangeOnlyState, pablo).length);
assert.equal(rangeOnlyState.scoutTokens, 1);
assert.equal(rangeOnlyState.scoutsThisGuess, 1);
assert.deepEqual(rangeOnlyState.scoutedStats.speed, speedRange);
assert.throws(() => scoutStat(rangeOnlyState, "speed", pablo));
state = submitGuess(state, PLAYERS[19], pablo);
assert.equal(state.scoutsThisGuess, 0);
assert.equal(Object.keys(state.guesses.at(-1).comparisons).length, CORE_STATS.length);
const equivalentPuzzle = createDailyPuzzle(PLAYERS, "2026-09-06", equivalentPair.id);
let equivalentState = createGameState(equivalentPuzzle);
equivalentState = submitGuess(equivalentState, equivalentGuess, equivalentPair);
assert.equal(equivalentState.status, "won");
const lossPuzzle = createDailyPuzzle(PLAYERS, "2026-09-07", pablo.id);
let lossState = createGameState(lossPuzzle);
for (const player of PLAYERS.filter((player) => player.id !== pablo.id).slice(0, 6)) {
	lossState = submitGuess(lossState, player, pablo);
}
assert.equal(lossState.status, "lost");
assert.equal(lossState.guesses.length, 6);
assert.equal(Object.keys(lossState.guesses.at(-1).comparisons).length, CORE_STATS.length);
console.log("Game logic checks passed.");